export enum AgentType {
  SALES = 'SALES',
  OPERATIONS = 'OPERATIONS',
  SUPPORT = 'SUPPORT',
  MARKETING = 'MARKETING',
  STRATEGY = 'STRATEGY',
  CHIEF_OF_STAFF = 'CHIEF_OF_STAFF',
  DESIGN = 'DESIGN',
  CUSTOM = 'CUSTOM',
}
