export enum BusinessSize {
  SOLO = 'SOLO',
  TWO_TO_TEN = 'TWO_TO_TEN',
  ELEVEN_TO_FIFTY = 'ELEVEN_TO_FIFTY',
  FIFTY_ONE_TO_ONE_HUNDRED = 'FIFTY_ONE_TO_ONE_HUNDRED',
  ONE_HUNDRED_ONE_TO_FIVE_HUNDRED = 'ONE_HUNDRED_ONE_TO_FIVE_HUNDRED',
  FIVE_HUNDRED_PLUS = 'FIVE_HUNDRED_PLUS',
}
