export enum BusinessIndustry {
  REAL_ESTATE = 'REAL_ESTATE',
  TECHNOLOGY = 'TECHNOLOGY',
  HEALTHCARE = 'HEALTHCARE',
  FINANCE = 'FINANCE',
  LEGAL = 'LEGAL',
  RETAIL = 'RETAIL',
  CONSTRUCTION = 'CONSTRUCTION',
  CONSULTING = 'CONSULTING',
  EDUCATION = 'EDUCATION',
  OTHER = 'OTHER',
}
