export enum CancellationReason {
  TOO_EXPENSIVE = 'TOO_EXPENSIVE',
  MISSING_FEATURES = 'MISSING_FEATURES',
  NOT_SEEING_VALUE = 'NOT_SEEING_VALUE',
  SWITCHING_PLATFORMS = 'SWITCHING_PLATFORMS',
  TECHNICAL_ISSUES = 'TECHNICAL_ISSUES',
  OTHER = 'OTHER',
}