export enum PackageType {
  AI_BUSINESS_LAUNCH = 'AI_BUSINESS_LAUNCH',
  CUSTOM_SUBSCRIPTION = 'CUSTOM_SUBSCRIPTION',
  DOWNGRADE_REQUEST = 'DOWNGRADE_REQUEST',
  SPECIALIST_CALL_REQUEST = 'SPECIALIST_CALL_REQUEST',
}