export enum TaskDepartment {
  SALES = 'SALES',
  FINANCE = 'FINANCE',
  OPERATIONS = 'OPERATIONS',
  STRATEGY = 'STRATEGY',
  SUPPORT = 'SUPPORT',
  DESIGN = 'DESIGN',
  MARKETING = 'MARKETING',
  OTHER = 'OTHER',
}
